//-----------------------------------------------------------------------------
//  Basler Data Processing SDK
//  Copyright (c) 2021-2023 Basler AG
//  http://www.baslerweb.com
//  Author:  BR
//-----------------------------------------------------------------------------
//
// This file is autogenerated. Changes will be overwritten.
// File contains pylon data processing version defines.

#pragma once

#define PYLON_DATAPROCESSING_VERSION_MAJOR           1
#define PYLON_DATAPROCESSING_VERSION_MINOR           3
#define PYLON_DATAPROCESSING_VERSION_SUBMINOR        0
#define PYLON_DATAPROCESSING_VERSION_BUILD           6089

#define PYLON_DATAPROCESSING_VERSIONSTRING_MAJOR     "1"
#define PYLON_DATAPROCESSING_VERSIONSTRING_MINOR     "3"
#define PYLON_DATAPROCESSING_VERSIONSTRING_SUBMINOR  "0"
#define PYLON_DATAPROCESSING_VERSIONSTRING_BUILD     "6089"
#define PYLON_DATAPROCESSING_VERSIONSTRING_EXTENSION "6089"

#define PYLON_DATAPROCESSING_GIT_REVISION            "23eaa6155b21d6d163a92ef457b4b7c853506e80"
#define PYLON_DATAPROCESSING_VERSION_SUFFIX          "_v1_3"
