#pragma once

#define MAX_TOP_CAM 2
#define MAX_SIDE_CAM 2
#define MAX_THREAD_COUNT 1
#define MAX_IMAGE_BUFFER_TOP 4
#define MAX_IMAGE_BUFFER_SIDE 8
#define FRAME_WIDTH_SIDE_CAM 2448
#define FRAME_HEIGHT_SIDE_CAM 2048
#define FRAME_WIDTH_TOP_CAM 2448
#define FRAME_HEIGHT_TOP_CAM 2048
//#define FRAME_WIDTH_TOP_CAM 4000
//#define FRAME_HEIGHT_TOP_CAM 3036
#define CHANNEL 3
#define FRAME_COUNT 1